-- Phase 1 seed: bullets (from scripts/build_resumes.js) + answers (from docs/ANSWER_LIBRARY.md)
-- Every bullet ships status='draft' regardless of proposed provenance below —
-- the provenance validator refuses anything not explicitly 'verified'.
-- Review docs/BULLET_LIBRARY_REVIEW.md, correct provenance where wrong, then flip
-- status to 'verified' per row (or in bulk) once confirmed.

insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-001', 'Specify, build, and deploy production-grade platforms as a single operator by directing AI coding agents — covering architecture, implementation, deployment, and iteration on work that would conventionally require a multi-person engineering team.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['ai agents','autonomy','delivery','systems architecture'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-002', 'Architected and launched an autonomous forecasting and decision-automation platform now running live in production — 68 API endpoints, 540 configurable strategy profiles, ensemble modeling, and automated risk controls with real-time hedging.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['production','live system','api design','risk automation','systems architecture'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-003', 'Designed the statistical validation layer governing production deployment: walk-forward optimization, 10,000-iteration Monte Carlo simulation, Bayesian estimation, Kelly-criterion position sizing, and drawdown and fee-sensitivity analysis.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['validation','testing','governance','production','risk'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-004', 'Led product design and go-to-market for an AI platform for small-business owners (in beta) that consolidates search visibility, content production, and cross-platform business intelligence — replacing an estimated $3,700–$9,500 per month of agency and freelance labor at a $49 per month price point.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['product','gtm','pricing','adoption','cost'], ARRAY['leadership'], 'modeled', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-005', 'Owned full product specification, scoring methodology, and pricing architecture; audited the platform’s own scoring engine and remediated 12 defects across three priority tiers before customer release.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['product','strategy','qa','validation','debugging'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-006', 'Took a consumer product from CAD design to launch-ready: supplier cost modeling across four vendors, component sourcing, direct-to-consumer storefront, and lifecycle email automation.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['product','sourcing','dtc','automation'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-007', 'Built the operational, financial, and compliance infrastructure that scaled top-line revenue from $250K to $12M in a single year, with $14M projected the following year.', 'COMARKCO', '2023-2025', ARRAY['scale','operations','impact','systems','finance'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-008', 'Secured $3M in working capital, inventory financing, and revolving credit to fund production and market entry, preventing supply interruption through peak demand.', 'COMARKCO', '2023-2025', ARRAY['finance','capital','operations'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-009', 'Designed and executed international expansion strategy across the Americas, Europe, Asia, and Oceania; launched Australia and Canada and established regulatory readiness for 20+ countries.', 'COMARKCO', '2023-2025', ARRAY['expansion','compliance','strategy','scale'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-010', 'Managed intellectual property, tax compliance, product safety certification, and import/export logistics for entry into regulated markets.', 'COMARKCO', '2023-2025', ARRAY['compliance','legal','operations'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-011', 'Scaled a cross-functional team from lean startup staff to 25 employees, improving retention and cross-department accountability.', 'COMARKCO', '2023-2025', ARRAY['leadership','team','change management','culture'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-012', 'Standardized and automated recurring finance, logistics, and reporting workflows, cutting manual processing time and removing bottlenecks across simultaneous multi-country operations.', 'COMARKCO', '2023-2025', ARRAY['workflow automation','process automation','efficiency','operations'], ARRAY['leadership','engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-013', 'Acted as Product Owner for the digital patient booking and reservation platform, owning requirements definition, user experience design, and cross-functional sprint planning.', 'WORKSITE LABS', '2020-2023', ARRAY['product','requirements','delivery','agile'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-014', 'Established the Project Management Office (PMO), creating governance and prioritization frameworks that standardized execution of cross-functional initiatives company-wide.', 'WORKSITE LABS', '2020-2023', ARRAY['governance','standards','pmo','change management'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-015', 'Developed and executed a company-wide customer experience strategy, improving CSAT and NPS scores and reducing churn.', 'WORKSITE LABS', '2020-2023', ARRAY['strategy','customer','adoption'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-016', 'Built partner onboarding frameworks that accelerated implementation timelines and standardized service quality across accounts.', 'WORKSITE LABS', '2020-2023', ARRAY['onboarding','process','partnerships'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-017', 'Designed and implemented the data infrastructure capturing customer feedback and engagement trends to inform executive decision-making.', 'WORKSITE LABS', '2020-2023', ARRAY['data','bi','internal tools'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-018', 'Managed a cross-functional engineering team using Agile and Scrum methodologies to deliver on-time, high-quality releases.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['leadership','agile','delivery'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-019', 'Built analytics and tracking systems for a proprietary advertising methodology, improving campaign targeting and performance.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['analytics','marketing tech','data'], ARRAY['leadership','engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-020', 'Automated ad-creation workflows with real-time analytics feedback, reducing iteration time on campaign production.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['workflow automation','marketing tech','analytics'], ARRAY['leadership','engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-021', 'Produced financial models and investor materials that supported successful fundraising efforts.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['finance','fundraising'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-022', 'Administered budgets for multiple research grants totaling $3.4M, ensuring funding compliance and accurate reporting.', 'UNIVERSITY OF CALIFORNIA, IRVINE', '2013-2018', ARRAY['finance','compliance','reporting'], ARRAY['leadership'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-023', 'Modernized departmental processes, reducing administrative turnaround time and operating cost.', 'UNIVERSITY OF CALIFORNIA, IRVINE', '2013-2018', ARRAY['process','efficiency'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-024', 'Built an alumni engagement program that strengthened department relationships and increased donation activity.', 'UNIVERSITY OF CALIFORNIA, IRVINE', '2013-2018', ARRAY['program','stakeholder'], ARRAY['leadership'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-025', 'Architected and shipped an autonomous forecasting and decision-automation platform running live in production — 68 API endpoints, 540 configurable strategy profiles, ensemble modeling, and automated risk controls with real-time hedging.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['production','live system','api design','risk automation','systems architecture'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-026', 'Built the statistical validation layer that gates production deployment: walk-forward optimization, 10,000-iteration Monte Carlo simulation, Bayesian estimation, Kelly-criterion sizing, and drawdown and fee-sensitivity analysis — no strategy reaches live execution without passing it.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['validation','testing','governance','production','risk'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-027', 'Specify, build, and deploy production-grade platforms as a single operator by directing AI coding agents, covering architecture, implementation, deployment, and iteration on work that would conventionally require a multi-person engineering team.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['ai agents','autonomy','delivery','systems architecture'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-028', 'Built an AI platform for small-business owners (in beta) integrating search visibility, automated content production, and a business-intelligence layer that unifies data across accounting, point-of-sale, and CRM systems.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['integration','internal tools','bi','data','product'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-029', 'Audited that platform’s scoring engine and remediated 12 defects across three priority tiers — including double-counted inputs and an image-analysis multiplier capable of depressing a score by over 90% from a single pass — before customer release.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['qa','validation','debugging','quality'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-030', 'Built data pipelines processing hundreds of thousands of records: batch classification and description generation via LLM APIs, vector embedding, dimensionality reduction, and nearest-neighbor computation.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['data pipelines','etl','llm','embeddings','scale'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-031', 'Reduced inference cost on production workloads through prompt-cache optimization and batch API usage rather than per-request calls.', 'BEAM LEGACY GROUP', '2025-Present', ARRAY['cost','optimization','llm','efficiency'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-032', 'Designed and implemented the operational, financial, and compliance systems that supported revenue growth from $250K to $12M in a single year.', 'COMARKCO', '2023-2025', ARRAY['systems','scale','operations','impact'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-033', 'Built the reporting and data infrastructure used for inventory planning, cash forecasting, and multi-entity financial consolidation.', 'COMARKCO', '2023-2025', ARRAY['data','bi','forecasting','reporting'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-034', 'Implemented compliance and documentation workflows for intellectual property, tax, product safety certification, and import/export logistics across 20+ countries.', 'COMARKCO', '2023-2025', ARRAY['compliance','workflow automation','operations'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-035', 'Integrated finance, e-commerce, and logistics platforms into a single reporting layer, eliminating manual reconciliation between systems.', 'COMARKCO', '2023-2025', ARRAY['integration','api','internal tools','data','systems'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-036', 'Product Owner for the digital patient booking and reservation platform — wrote requirements, designed the user experience, and ran sprint planning with engineering through delivery.', 'WORKSITE LABS', '2020-2023', ARRAY['product','requirements','delivery','agile'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-037', 'Designed and implemented the data infrastructure capturing customer feedback and engagement telemetry, and built the reporting layer executives used for decision-making.', 'WORKSITE LABS', '2020-2023', ARRAY['data','telemetry','bi','internal tools'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-038', 'Built partner onboarding workflows that shortened implementation timelines and standardized data handoffs across accounts.', 'WORKSITE LABS', '2020-2023', ARRAY['workflow automation','onboarding','process'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-039', 'Instrumented CSAT and NPS measurement and used the resulting data to prioritize product and process fixes.', 'WORKSITE LABS', '2020-2023', ARRAY['data','product','process'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-040', 'Ran delivery for a cross-functional engineering team using Agile and Scrum, writing requirements and coordinating releases.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['agile','delivery','requirements'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-041', 'Built financial models and data-driven investor materials supporting successful fundraising.', 'STAIRCASE DIGITAL / WHEELHOUSE STUDIO', '2018-2020', ARRAY['finance','fundraising','data'], ARRAY['engineer'], 'stated', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-042', 'Administered and reported on research grant budgets totaling $3.4M, building the tracking and compliance reporting used across multiple funded projects.', 'UNIVERSITY OF CALIFORNIA, IRVINE', '2013-2018', ARRAY['finance','compliance','reporting'], ARRAY['engineer'], 'measured', 'draft');
insert into bullets (ref, text, source_org, source_period, tags, variants, provenance, status) values ('BL-043', 'Automated and streamlined departmental administrative processes, reducing turnaround time and operating cost.', 'UNIVERSITY OF CALIFORNIA, IRVINE', '2013-2018', ARRAY['process','automation','efficiency'], ARRAY['engineer'], 'stated', 'draft');

-- answers table, schema per docs/ANSWER_LIBRARY.md
create table answers (
  id            bigserial primary key,
  ref           text unique not null,     -- A2
  question_type text not null,            -- why_company | automation_experience | ...
  text          text not null,
  slots         text[],                   -- {{company}}, {{specific_signal}}
  status        text default 'ready',     -- ready|draft|needs_input
  tags          text[],
  times_used    int default 0,
  last_used_at  timestamptz
);

-- READY / DRAFT entries seeded with their actual text. NEEDS YOU entries (A3, B1-B7)
-- are seeded with the *prompt describing what's needed*, never a fabricated answer —
-- their text field is what to fill in, not an answer.

insert into answers (ref, question_type, text, slots, status, tags) values
('A1', 'why_company', 'What caught me about {{company}} is {{specific_signal}} — that''s the exact problem I''ve spent the last year on. I''ve been building AI automation systems end to end, most recently an autonomous decision platform running live in production, and what I want next is to do that inside an organization where the leverage is bigger than a five-person shop. {{role_specific_hook}}', ARRAY['company','specific_signal','role_specific_hook'], 'draft', ARRAY['why_company']),
('A2', 'automation_experience', E'I build and operate production AI systems rather than pilots. The clearest example: an autonomous forecasting and decision-automation platform I architected and shipped that runs live today — 68 API endpoints, 540 configurable strategy profiles, ensemble modeling, and automated risk controls with real-time hedging. I also built the statistical validation layer that gates it, so no strategy reaches live execution without passing walk-forward testing, Monte Carlo simulation, and drawdown analysis.\n\nBefore the technical work I spent twelve years running operations — scaling a CPG brand from $250K to $12M, building the finance, logistics, and compliance systems behind it. That combination is the useful part: I build automations against how a business actually runs, not against an idealized process diagram.', NULL, 'ready', ARRAY['automation_experience']),
('A3', 'why_leaving_own_company', 'NEEDS INPUT: draft exists from a past conversation but is unconfirmed — see docs/ANSWER_LIBRARY.md A3 for the drafted text and confirm before this ships.', NULL, 'needs_input', ARRAY['why_leaving']),
('A4', 'ic_vs_leadership', 'I''ve done the leadership track and I''m good at it. I''m better at building, and I enjoy it more. I''m looking for a role where the deliverable is a working system rather than a headcount plan. I''m not looking to manage people, and I''d rather say that clearly up front than discover a mismatch in month three.', NULL, 'ready', ARRAY['ic_vs_leadership']),
('A5', 'salary_expectations', '{{target_range}} base, flexible depending on total package and equity.', ARRAY['target_range'], 'ready', ARRAY['salary']),
('A6', 'biggest_system_built', 'NEEDS INPUT: composed from A2''s first paragraph plus an additional closing line — see docs/ANSWER_LIBRARY.md A6 for the full text.', NULL, 'draft', ARRAY['biggest_system']),
('A7', 'tell_me_about_a_failure', E'While drafting a resume I caught a bullet describing an internal system as built and deployed. I''d specified it in detail. I hadn''t shipped it. Nothing in my notes distinguished those two states — six weeks on, an ambitious plan and a running system read identically — and it was one screen-share question away from being indefensible.\n\nThe fix was structural, not a promise to be more careful: every claim in my library now carries a provenance tag, and a ten-line validator refuses to assemble a document containing an unverifiable one.\n\nThe general version matters more than the resume version. When a language model summarizes your own notes back to you, it will quietly promote intention to accomplishment, and it will do it in your voice. Any system putting model output in front of people needs a layer that asks where each claim came from.', NULL, 'ready', ARRAY['failure']),
('A8', 'ai_deployment_philosophy', E'Start with where the blast radius lands, not with what''s possible. The capability is usually trivial now; the question is what breaks when it''s wrong and who finds out.\n\nA concrete example: I built a pipeline for my own job search that automates discovery, screening, and document assembly. The version that also auto-submits applications was about three more hours of work. I didn''t build it — ATS terms prohibit it, the platforms detect it, and a flag in a shared instance quietly costs you every company on that platform. Most AI deployment decisions look like that.\n\nSecond thing: choose the boring architecture. That pipeline has no vector store and no agent framework, because the corpus is a few hundred rows and keyword matching plus one model call is correct. Reaching for the sophisticated option when the simple one works is the most common failure I see in AI projects right now.', NULL, 'draft', ARRAY['ai_philosophy']),
('A9', 'automation_philosophy_oneline', 'Automate the work, keep the human on the decisions that have consequences — and be deliberate about which is which.', NULL, 'draft', ARRAY['automation_philosophy']),
('A10', 'domain_gap', 'I haven''t. What I have is twelve years of learning new operating environments fast — CPG, healthcare services, digital media, higher ed — and the automation problems rhyme across all of them: manual reconciliation between systems, reporting nobody trusts, workflows that exist because someone left. I''d expect the first month to be mostly listening.', ARRAY['industry'], 'draft', ARRAY['domain_gap']),
('B1', 'influence_without_authority', 'NEEDS INPUT: a specific instance of influencing a team you didn''t own, likely from Comarkco as a fractional exec. No draft exists — see docs/ANSWER_LIBRARY.md B1.', NULL, 'needs_input', ARRAY['behavioral']),
('B2', 'conflict_or_disagreement', 'NEEDS INPUT: a specific instance of a real conflict/disagreement. No draft exists — see docs/ANSWER_LIBRARY.md B2.', NULL, 'needs_input', ARRAY['behavioral']),
('B3', 'reference_safe_reason_for_leaving', 'NEEDS INPUT: reference-check-safe framing for leaving Worksite Labs and Comarkco — what actually happened and what those employers would say. Shapes several other answers. No draft exists — see docs/ANSWER_LIBRARY.md B3.', NULL, 'needs_input', ARRAY['reason_for_leaving']),
('B4', 'availability_start_date', 'NEEDS INPUT: availability / notice period. No draft exists — see docs/ANSWER_LIBRARY.md B4.', NULL, 'needs_input', ARRAY['logistics']),
('B5', 'comarkco_equity_outcome', 'NEEDS INPUT: whether the Comarkco equity paid off — materially affects how A3 should be framed. No draft exists — see docs/ANSWER_LIBRARY.md B5.', NULL, 'needs_input', ARRAY['equity']),
('B6', 'three_year_vision', 'NEEDS INPUT: what you actually want to be doing in three years — needs careful framing around the ventures, not an invented ambition. No draft exists — see docs/ANSWER_LIBRARY.md B6.', NULL, 'needs_input', ARRAY['career_vision']),
('B7', 'recurring_interview_stumper', 'NEEDS INPUT: any question that has reliably tripped you up in past interviews — highest-value entry in this file once filled. No draft exists — see docs/ANSWER_LIBRARY.md B7.', NULL, 'needs_input', ARRAY['interview_prep']);

